### ISSUE TITLE
项目根目录下的 .fecsrc 文件不起作用

### ISSUE THREAD

**Issue by bruce-xu** [cxtom/fecs-git-hooks#2]
发现项目根目录下的 .fecsrc 文件里的配置不起作用。在命令行下执行 fecs xx.js 发现 .fecsrc 里的配置有效，但 git commit 时，发现 .fecsrc 里的配置无效，还是按照默认的规则作检查。

**Comment by cxtom** [comment]
已修复，0.1.1
